//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Slutty_ryze.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Slutty_ryze.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to             ___                                              
        ///    _.-~~   ~~~-.                                         
        ///   /         _   ~.                                       
        ///  |#`       /#`    \     They asked me what i wanted to be
        ///  |-&apos;|      |-&apos;|    |                                     
        ///  /--        --     |-.      I said BE A SQUIRTLE            
        ///  \__   .  .        / /\_                                 
        ///   \ ~~--___---~~/\| |   ~-.                              
        ///.---`~~--____---_)  \ \-__ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string display {
            get {
                return ResourceManager.GetString("display", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to `&apos;:,,,,,;:                                                           
        ///                             ;:,.,,,,,,,,:+                                                         
        ///                            +,,,..,,,,,,,,:&apos;`                                                       
        ///                          `,.``...,,,,,,,,,:+                                                       
        ///                         .,.```...,,,,,,,,,::#                                                      
        ///                         :,```... [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string display2 {
            get {
                return ResourceManager.GetString("display2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to `@                                                                           
        ///                       @@                                                                           
        ///                      @@@                                                                           
        ///                     +@@@                                                                           
        ///                     @@@@`                                                                          
        ///                    @@@@@ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string display3 {
            get {
                return ResourceManager.GetString("display3", resourceCulture);
            }
        }
    }
}
