//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.CodeDom.Compiler;
using System.ComponentModel;
using System.Diagnostics;
using System.Diagnostics.CodeAnalysis;
using System.Globalization;
using System.Resources;
using System.Runtime.CompilerServices;

namespace Slutty_ryze.Properties {
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [GeneratedCode("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [DebuggerNonUserCode()]
    [CompilerGenerated()]
    internal class Resources {
        
        private static ResourceManager resourceMan;
        
        private static CultureInfo resourceCulture;
        
        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        internal static ResourceManager ResourceManager {
            get {
                if (ReferenceEquals(resourceMan, null)) {
                    ResourceManager temp = new ResourceManager("Slutty_ryze.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        internal static CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to                _,........__
        ///            ,-&apos;            &quot;`-.
        ///          ,&apos;                   `-.
        ///        ,&apos;                        \
        ///      ,&apos;                           .
        ///      .&apos;\               ,&quot;&quot;.       `
        ///     ._.&apos;|             / |  `       \
        ///     |   |            `-.&apos;  ||       `.
        ///     |   |            &apos;-._,&apos;||       | \
        ///     .`.,&apos;             `..,&apos;.&apos;       , |`-.
        ///     l                       .&apos;`.  _/  |   `.
        ///     `-.._&apos;-   ,          _ _&apos;   -&quot; \  .     `
        ///`.&quot;&quot;&quot;&quot;&quot;&apos;-.`-...,---------&apos;,&apos;         `. [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string display {
            get {
                return ResourceManager.GetString("display", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to            _.--&quot;&quot;`-..
        ///            ,&apos;          `.
        ///          ,&apos;          __  `.
        ///         /|          &quot; __   \
        ///        , |           / |.   .
        ///        |,&apos;          !_.&apos;|   |
        ///      ,&apos;             &apos;   |   |
        ///     /              |`--&apos;|   |
        ///    |                `---&apos;   |
        ///     .   ,                   |                       ,&quot;.
        ///      ._     &apos;           _&apos;  |                    , &apos; \ `
        ///  `.. `.`-...___,...---&quot;&quot;    |       __,.        ,`&quot;   L,|
        ///  |, `- .`._        _,-,.&apos;   .  __.-&apos;-. /        .   ,    \
        ///-: [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string display2 {
            get {
                return ResourceManager.GetString("display2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to                                                   /
        ///                        _,.------....___,.&apos; &apos;,.-.
        ///                     ,-&apos;          _,.--&quot;        |
        ///                   ,&apos;         _.-&apos;              .
        ///                  /   ,     ,&apos;                   `
        ///                 .   /     /                     ``.
        ///                 |  |     .                       \.\
        ///       ____      |___._.  |       __               \ `.
        ///     .&apos;    `---&quot;&quot;       ``&quot;-.--&quot;&apos;`  \               .  \
        ///    .  ,            __         [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string display3 {
            get {
                return ResourceManager.GetString("display3", resourceCulture);
            }
        }
    }
}
